[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../vendor/core", optional = true }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
strip = true
