[build]
target = "targets/neobench-m68k.json"

[target.neobench-m68k]
rustflags = ["-C", "target-feature=-atomic"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
