cargo-features = ["edition2024"]
[package]
name = "neobench"
version = "0.1.0"
edition = "2024"

[dependencies]
boot = { path = "../boot" }
kernel = { path = "../kernel" }
gui = { path = "../gui" }

[lib]
path = "main.rs"
crate-type = ["staticlib"]
