[package]
name = "neoboot"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = false

[lib]
crate-type = ["rlib"]
